src/plugins/undo-plugin.js

This PR allows to pass custom tracked origins to `UndoManager` from `undo-plugin`.
Closes: #9

Customize tracked origins

---

src/plugins/sync-plugin.js

The following commit allows y-prosemirror to work with documents with forced, custom layouts. An example of this is a document with a required title, with the schema defined as `content: "title block+"`.
Previously, it was assumed that an empty ProseMirror document is a single paragraph node, with content size of 2. As a result, when ProseMirror initializes an empty document with a custom layout (with content size > 2), the sync-plugin erroneously triggers a call to `binding._prosemirrorChanged` even though the initial content has not changed. 
Because of this, yjs will not be able to initialize a serialized document correctly with `Y.applyUpdate(ydoc, ystate)`: instead of merging the nodes from `ystate` and the empty nodes created by the ProseMirror layout, it will duplicate the nodes. …

custom document layouts with y-prosemirror

---

src/plugins/sync-plugin.js

What Happens:
1. There are 2 different clients connected to the same room (ClientA, ClientB) and they both have the cursor on the same prose mirror view (and thus both are focused on the view).
2. ClientA sets the cursor somewhere in the text field and scrolls up or down until the cursor is outside of the view.
3. ClientB types something in the same text field (it does not matter where).
Expected behaviour:
The view of ClientA should not scroll because the cursor of this client is not visible in the browser. 
Actual behaviour:
The view of ClientA will be scrolled back to where the client previously placed cursor.
Note: The issue is only reproducable with 2 different computers. If not the prose mirror view of one of the clients will lose focus when going the the other browser window.

Unexpected scroll in the prose mirror view by yjs update

---

README.md
package-lock.json
package.json
rollup.config.js
src/interface.js
src/lib.js
src/plugins/cursor-plugin.js
src/plugins/keys.js
src/plugins/sync-plugin.js
src/plugins/undo-plugin.js
src/y-prosemirror.js

As discussed here: https://discuss.yjs.dev/t/prosemirror-serializer/240
This PR adds new methods to aid getting content into and out of Y.Doc format for Prosemirror users. As part of this I had to move some more generic methods out of the `syncPlugin` and up to the `lib`, I also pulled the plugin keys to a higher level to avoid circular dependencies. 
`yDocToProsemirrorJSON` Is probably not _perfect_ yet, there might be an edge case I haven't covered, but that should become readily apparent in production usage soon.
Edit: I've published a fork with these utilities `@tommoor/y-prosemirror`

feat: Add utility methods for conversion to/from Prosemirror

---

src/plugins/cursor-plugin.js

Event listeners should be removed when plugin is destroyed.

Fixed event listener memory leak

---

src/plugins/sync-plugin.js

I have a few situations where I'd like to keep an already built yDoc in memory (for example, a large one that took a while to parse) and re-use it later. The sync-plugin, however, doesn't seem to expect that behavior, and doesn't clean up the transaction observers on the Prosemirror Plugin destroy hook. This leads to duplicate work and increased processing time on each subsequent re-use.
In this change, I save the transaction hooks as local properties in the ProsemirrorBinding, and remove them in the destroy lifecycle method.

Clean up yDoc observers on PM plugin destroy

---

src/plugins/sync-plugin.js

Use ProseMirror method [`findDiffStart`](https://prosemirror.net/docs/ref/#model.Fragment.findDiffStart) to compare / diff documents instead of converting to JSON and then using lib0's [`equalityDeep`](https://github.com/dmonad/lib0/blob/main/function.js#L78):
```diff
- !fun.equalityDeep(view.state.doc.type.createAndFill().content.toJSON(), view.state.doc.content.toJSON())
+ view.state.doc.content.findDiffStart(view.state.doc.type.createAndFill().content) != null
```
Reasoning is `equalityDeep` fails on two equal JSON objects created by ProseMirror's `toJSON()`, because ProseMirror [uses `Object.empty(null)` to initialize node attrs](https://github.com/ProseMirror/prosemirror-model/search?q=Object.create%28null%29), which results in `equalityDeep` returning false because …

Use `findDiffStart` instead of `equalityDeep`

---

src/plugins/sync-plugin.js

So this is continuation for #66 and it is the fix I have been using with a locally linked version of `y-prosemirror`. Why I need this is because I'm intercepting transactions as in track changes functionality and I can't really detect whether the transaction was originally from ProseMirror or from ySyncPlugin.
With the added booleans in the meta field I can omit those transaction that are caused by for example rendering a snapshot. Also I think it is better DX if you can immediately see from a transaction that "ah this was dispatched by ySyncPlugin". It doesn't seem there are major downsides, without having the meta payload typed it is I guess a little harder to see what are the passed values.

Use setMeta for all trs dispatched by ySyncPlugin

---

src/plugins/sync-plugin.js

As described in https://github.com/yjs/y-prosemirror/issues/83 this is the proposed fix. Not sure would you @dmonad prefer inlining the condition. I used a function since it felt a little cleaner.

Check for object nullness in equalAttrs

---

src/plugins/cursor-plugin.js

This is modelled similar to the existing "cursor builder"; note that with this change the selection
is now tagged with the `ProseMirror-yjs-selection` class as well.
See https://github.com/yjs/y-prosemirror/pull/55#issuecomment-1055169237; I'll would propose to close that PR in favor of this one.

Extract determining the attributes used for the selection into a configurable "selection builder"

---

src/plugins/sync-plugin.js

Not clearing the timeout causes issues where code is run after the `EditorView` and its plugins have already been destroyed. In our app this resulted in two errors that manifested in different cases where the editor view was being unmounted:
- `Uncaught TypeError: Cannot read properties of null (reading 'matchesNode')`
- `Uncaught RangeError: Applying a mismatched transaction`
Both errors were fixed by applying the monkey patch kindly provided by @hoebbelsB in #70.
This PR implements that fix in `sync-plugin` so that we could stop monkey patching it.

Clear timeout when destroying plugin

---

src/plugins/sync-plugin.js

Changes coming through Yjs are not changes from the local user, but rather they represent
changes in other places in the system. Such changes do not need to be tracked and made
undo-able. This plugin also triggers prosemirror changes when rendering snapshots
and when forcing re-renders, which do a full document replace step.
By marking these with the `"addToHistory"` meta the [prosemirror-history plugin](https://prosemirror.net/docs/ref/#history) will be
able to ignore these changes for the purposes of providing undo/redo functionality on the
editor model level, without affecting a Yjs document level undo/redo.
---
See also https://discuss.yjs.dev/t/avoiding-y-prosemirror-undo/985

Mark all transactions originating from the sync-plugin as "not for history"

---

package.json

These files are _big_, and completely unneeded when using y-prosemirror.

Exclude the tests from packaging for npm

---

src/lib.js

Fix:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'binding')
```
when removing the plugins from prosemirror state. It seems that an awareness event from yCursorPlugin is received and processed after the plugins are destroyed.
To reproduce:
```
diff --git a/demo/prosemirror.js b/demo/prosemirror.js
index a1cc530..7712a19 100644
--- a/demo/prosemirror.js
+++ b/demo/prosemirror.js
@@ -18,21 +18,21 @@ window.addEventListener('load', () => {
editor.setAttribute('id', 'editor')
const editorContainer = document.createElement('div')
editorContainer.insertBefore(editor, null)
-  const prosemirrorView = new EditorView(editor, {
-    state: EditorState.create({
-      schema,
-      plugins: [
-        ySyncPlugin(type),
-        yCursorPlugin(provider.awareness),
- …
```

add null check for syncState

---

src/lib.js
src/plugins/sync-plugin.js
src/y-prosemirror.js
test/y-prosemirror.test.js

Adds new methods `prosemirrorToYXmlFragment`, `prosemirrorJSONToYXmlFragment`, `yXmlFragmentToProsemirror`, and `yXmlFragmentToProsemirrorJSON` to support direct PM <=> YXmlFragment conversion.
Note there's a small hack in `prosemirrorToYXmlFragment` to allow independent creation of Y.XmlFragment before the Y.Doc exists (supporting bottom-up tree construction)
Fixes #50

Add support for converting directly between prosemirror and Y.XmlFragment nodes

---

.gitignore
src/plugins/sync-plugin.js

Happy to rename if you feel like this should be a different name.
The goal with this is to know when the initial yjs-prosemirror sync has finished so that I can do something else

Add on initial apply callback

---

README.md

- Adds a readme section on undos
- Proposes a way to prevent some changes from being undone per discussion in https://github.com/yjs/y-prosemirror/issues/110
The proposed API mirrors prosemirror-history, for more info see https://github.com/ProseMirror/prosemirror-history/blob/master/src/history.js#L380

Readme section for undo/redo, proposed addToHistory command

---

src/plugins/sync-plugin.js

I encountered an error `TypeError: Cannot read property 'matchesNode' of null` when using with react and HMR.
(same as https://github.com/ueberdosis/tiptap/issues/1451)
I just found that y-prosemirror dispatches a transaction even after destroyed, and it's due to failed to clear timeout by wrong use of `lib0/eventloop`.

Fix wrong timeout object

---

package-lock.json
package.json

`y-prosemirror` doesn't depend on `typescript` during runtime, so I guess `typescript` should be moved to `devDependencies`.

move typescript to devDependencies

---

src/plugins/cursor-plugin.js

This option is needed when we want to remove self "cursor" when opened N-tabs or other logic.
For example, in "GoogleDocs", this is exactly the behavior, they display N-1 "cursors" (N — number of tabs), but in the case of "Notion", they do not display their own "cursor".
```js
yCursorPlugin(provider.awareness, {
awarenessStateFilter: (_, __, user) => user.id !== getAuthUserId(),
})
```

feat: Added `awarenessStateFilter` option for filtering `awareness.getState()`

---

README.md

Version 1.0.17 removed .travis.yml and now the build status is broken.
If travis is reimplemented then the link is to https://app.travis-ci.com/github/yjs/y-prosemirror

Removed reference to travis in readme

---

src/plugins/sync-plugin.js

Fixes https://github.com/yjs/y-prosemirror/issues/170.

fix: avoid throwing an exception if the current selection no longer makes sense when initializing ySyncPlugin

---

src/lib.js

This fixes an issue introduced in 1.3.0 where the signature of `initProseMirrorDoc` was changed in a backwards-incompatible way.
This introduces the intended change in a backwards-compatible and user-friendly way by providing both the mapping (which they may need for the sync plugin) and the meta binding (which they may need for updateYFragment like I did)

fix: return both mapping and meta

---

src/plugins/sync-plugin.js

This PR updates the `restoreRelativeSelection` method to use [`TextSelection.between`](https://prosemirror.net/docs/ref/#state.TextSelection%5Ebetween) instead of [`TextSelection.create`](https://prosemirror.net/docs/ref/#state.TextSelection%5Ecreate) when restoring a text selection. This resolves an issue where the text selection may be pointing "between" nodes which are invalid to have text selections into. The `TextSelection.between` method will account for this and try to restore the selection into an appropriate position.
Prosemirror has it's own concept of a relative position (via [bookmarks](https://prosemirror.net/docs/ref/#state.SelectionBookmark)) which can be mapped across transactions. And, the mapping can sometimes [produce invalid positions (relative to the selection …

fix: use TextSelection.between for restoring the selection

---

src/plugins/keys.js
src/plugins/sync-plugin.js
src/plugins/undo-plugin.js

This refactors the `undo-plugin` to:
- add TypeScript types for the `undo-plugin` state
- add new `undoCommand` and `redoCommand` exports which will only modify the state if `dispatch` is present
- `undoCommand` and `redoCommand` now only undo/redo if there is something to actually undo/redo
I made these as separate commands since this was going to be a breaking change for existing users (since `dispatch` is now required to execute).
This is more in-line with how prosemirror intends things to work. Where it can be useful to have a command run without the dispatch function to see if the command can run (e.g. to enable/disable undo & redo buttons).
This is also matching the implementation set forth by prosemirror-history, making it trivial to replace the two implementations

Add `undoCommand` & `redoCommand` for prosemirror-history compatible API

---

src/plugins/sync-plugin.js
tests/y-prosemirror.test.js

When inserting content between existing nodes, the sync logic incorrectly updated the last paragraph instead of inserting a new paragraph before it.
| `<h1>Heading</h1>`    | `<h1>Heading</h1>`    |
|---------------------|--------------------|
| `<p>Paragraph 1</p>`  | `<p>Paragraph 1</p>`  |
| `<p>Paragraph 2</p>`  | `<p></p>`             |
| `<p></p>`             |                     |
| ProseMirror         | Matched Yjs Elem     | Result Yjs Elem             |
|---------------------|----------------------|-----------------------------|
| `<h1>Heading</h1>`    | = `<h1>Heading</h1>`   | `<h1>Heading</h1>`            |
| `<p>Paragraph 1</p>`  | = `<p>Paragraph 1</p>` | `<p>Paragraph 1</p>`          |
| `<p>Paragraph 2</p>`  |   `<p></p>`            | `<p>Paragraph 2</p>` UPDATED  |
| …

Fix incorrect node updates by wrong right side match
